import { seedLegacyObject } from './helpers/focused-product.js';
import { downloadUpdated } from './helpers/focused-product.js';
import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdir, writeFile, readFile } from 'node:fs/promises';
import { resolve, join } from 'node:path';
import { pathToFileURL } from 'node:url';
import { chromium, type Page } from 'playwright';
import { enhanceHTML } from '../packages/html-document/src/index.js';
const out=resolve('artifacts/ui02');
const source=`<title>UI02 · 原生对象</title><style>body{margin:0}section{padding:32px;box-sizing:border-box;min-height:650px;background:white}h1{font:32px system-ui}.content{display:flex;flex-direction:column;gap:12px}.grid{display:grid;grid-template-columns:1fr 1fr}button{color:red!important}</style><section data-ppte-slide data-ppte-id="s1"><h1 data-ppte-id="title" style="position:absolute;top:0;left:400px;z-index:4">作者标题</h1><div class="content" data-ppte-content data-ppte-id="container"><p data-ppte-id="text">作者文字</p><p data-ppte-id="locked" data-ppte-locked="true">保护文字</p></div></section><section data-ppte-slide data-ppte-id="s2"><div class="grid" data-ppte-id="grid"><p data-ppte-id="g1">Grid 一</p><p data-ppte-id="g2">Grid 二</p></div></section><section data-ppte-slide data-ppte-id="s3"><p data-ppte-id="flow">普通文档流</p></section>`;
async function setup(name:string){await mkdir(out,{recursive:true});const file=join(out,name+'.ppte.html');await writeFile(file,(await enhanceHTML(source,{root:out,base:out})).html);const browser=await chromium.launch({channel:'chrome',headless:true});const context=await browser.newContext({offline:true,viewport:{width:1440,height:1000},acceptDownloads:true});const p=await context.newPage();const errors:string[]=[],network:string[]=[];p.on('pageerror',e=>errors.push(String(e)));p.on('request',r=>{if(/^https?:/.test(r.url()))network.push(r.url());});await p.goto(pathToFileURL(file).href);await p.waitForFunction(()=>!!(window as any).PPTeSave);await p.getByRole('button',{name:'编辑',exact:true}).click();return {p,browser,async close(){try{assert.deepEqual(errors,[]);assert.deepEqual(network,[]);await writeFile(join(out,name+'.json'),JSON.stringify({browser:browser.version(),headless:true,entry:'file://',offline:true,errors,network,timestamp:new Date().toISOString(),verdict:'See node --test TAP assertions; capture alone is not a pass'},null,2));}finally{await browser.close();}}};}
const frame=(p:Page)=>p.frameLocator('#ppte-frame');
// F01: legacy objects are seeded as command fixtures, not exposed insertion controls.
async function insert(p:Page,label:string,child?:string){await seedLegacyObject(p,label==='文本框'?'text':label==='表格'?'table':child==='椭圆'?'ellipse':child==='线条'?'line':'rect',3,3);}

async function property(p:Page,label:string,value:string){const input=p.getByLabel(label,{exact:true});if(!await input.isVisible())await p.locator('#ppte-properties summary').filter({hasText:'位置与布局'}).click();if(await input.evaluate(n=>n.tagName)==='SELECT')await input.selectOption(value);else{await input.fill(value);await input.press('Tab');}}
const selected=(p:Page)=>frame(p).locator('[data-ppte-editor-selected]');
test('UI02 acceptance 1: command-seeded legacy object fixtures adjust through UI and survive actual download / fresh process',async()=>{const f=await setup('objects');const p=f.p;try{
 await frame(p).locator('[data-ppte-id=text]').click({position:{x:8,y:8}});await insert(p,'文本框');await selected(p).fill('新增文本');await property(p,'字体','serif');await property(p,'字号','30px');await p.getByRole('button',{name:'粗体',exact:true}).click();assert.equal(await selected(p).evaluate(n=>{const walk=n.ownerDocument.createTreeWalker(n,NodeFilter.SHOW_TEXT);let t;while(t=walk.nextNode())if(t.textContent?.trim()&&getComputedStyle(t.parentElement!).fontWeight!=='700')return false;return n.textContent==='新增文本';}),true,'every rendered text run is bold, including native range spans');
 await insert(p,'形状','椭圆');await property(p,'填充','#ff0000');await property(p,'边框宽度','3px');await property(p,'宽度','180px');assert.equal(await selected(p).evaluate(n=>getComputedStyle(n).backgroundColor),'rgb(255, 0, 0)');
 await insert(p,'形状','线条');assert.equal(await p.getByLabel('填充',{exact:true}).count(),0);await property(p,'边框颜色','#008800');
 await insert(p,'形状','矩形');await property(p,'圆角','12px');assert.equal(await selected(p).evaluate(n=>getComputedStyle(n).borderRadius),'12px');const width=await selected(p).evaluate(n=>n.getBoundingClientRect().width);await p.getByRole('button',{name:'调整对象大小',exact:true}).press('ArrowRight');assert.equal(await selected(p).evaluate(n=>n.getBoundingClientRect().width),width+8);await p.getByRole('button',{name:'撤销',exact:true}).click();assert.equal(await selected(p).evaluate(n=>n.getBoundingClientRect().width),width);
 const png=await p.screenshot({clip:{x:0,y:0,width:48,height:32}});
 const chooser=p.waitForEvent('filechooser');await p.getByRole('button',{name:'插入图片',exact:true}).click();await(await chooser).setFiles({name:'local.png',mimeType:'image/png',buffer:png});await p.waitForFunction(()=>!!(window as any).PPTeEditor.commands.doc.querySelector('img[data-ppte-editor-selected]'));
 const src=await selected(p).getAttribute('src');await p.getByRole('button',{name:'填充裁切',exact:true}).click();await property(p,'水平焦点（0–100%）','25');assert.equal(await selected(p).evaluate(n=>getComputedStyle(n).objectPosition),'25% 50%');assert.equal(await selected(p).getAttribute('src'),src);
 await p.getByRole('button',{name:'重置裁切',exact:true}).click();assert.equal(await selected(p).evaluate(n=>getComputedStyle(n).objectFit),'contain');
 await insert(p,'表格','3 行 3 列');const table=frame(p).locator('table');await table.locator('tr').nth(1).locator('td').nth(1).click();await selected(p).fill('中间单元格');await property(p,'单元格填充','#ffff00');assert.match(await p.locator('#ppte-properties').textContent()??'',/第 2 行 \/ 第 2 列/);
 await p.getByRole('button',{name:'删除当前行',exact:true}).click();assert.equal(await table.locator('tr').count(),2);assert.doesNotMatch(await table.textContent()??'',/中间单元格/);
 await p.getByRole('button',{name:'撤销',exact:true}).click();assert.equal(await table.locator('tr').count(),3);assert.match(await table.textContent()??'',/中间单元格/);
 await table.locator('tr').nth(1).locator('td').nth(1).click();await p.getByRole('button',{name:'删除当前列',exact:true}).click();assert.equal(await table.locator('tr').first().locator('td').count(),2);await p.getByRole('button',{name:'撤销',exact:true}).click();
 await table.locator('td').first().click();await p.getByRole('button',{name:'添加行',exact:true}).click();assert.equal(await table.locator('tr').count(),4);await p.getByRole('button',{name:'添加列',exact:true}).click();assert.equal(await table.locator('tr').first().locator('td').count(),4);
 await p.screenshot({path:join(out,'objects.png')});const dl=p.waitForEvent('download');await downloadUpdated(p);const saved=join(out,'sample.ppte.html');await(await dl).saveAs(saved);assert.equal(/<div[^>]*id="ppte-insert-menu"/.test(await readFile(saved,'utf8')),false,'transient menu DOM must not be exported (runtime implementation remains embedded)');
 const fresh=await chromium.launch({channel:'chrome',headless:true});try{const q=await fresh.newPage();await q.context().setOffline(true);await q.goto(pathToFileURL(saved).href);await q.waitForFunction(()=>!!(window as any).PPTeSave);assert.equal(await q.locator('#ppte-save-ui').getAttribute('data-mode'),'read');assert.equal(await frame(q).locator('[data-ppte-kind=text]').textContent(),'新增文本');assert.equal(await frame(q).locator('[data-ppte-kind=shape]').count(),3);assert.equal(await frame(q).locator('table tr').count(),4);assert.equal(await frame(q).locator('img').evaluate(n=>(n as HTMLImageElement).naturalWidth),48);}finally{await fresh.close();}
 }finally{await f.close();}});
test('UI02 acceptance 2: command fixture placement follows author Flex/Grid/flow and retains positioned author CSS',async()=>{const f=await setup('layout');const p=f.p;try{
 const author=await frame(p).locator('[data-ppte-id=title]').getAttribute('style');
 await frame(p).locator('[data-ppte-id=title]').click();await p.locator('#ppte-properties summary').filter({hasText:'位置与布局'}).click();await p.getByLabel('对齐基准',{exact:true}).selectOption('page');await p.getByRole('button',{name:'向左对齐',exact:true}).click();assert.ok(await selected(p).evaluate(n=>Math.abs(n.getBoundingClientRect().left-n.closest('[data-ppte-slide]')!.getBoundingClientRect().left)<.1));await p.getByRole('button',{name:'撤销',exact:true}).click();
 await frame(p).locator('[data-ppte-id=text]').click({position:{x:8,y:8}});await insert(p,'形状','矩形');assert.equal(await selected(p).evaluate(n=>n.parentElement?.getAttribute('data-ppte-id')),'container');assert.notEqual(await selected(p).evaluate(n=>getComputedStyle(n).position),'absolute');assert.equal(await frame(p).locator('[data-ppte-id=container]').evaluate(n=>getComputedStyle(n).display),'flex');assert.equal(await frame(p).locator('[data-ppte-id=title]').getAttribute('style'),author);await property(p,'顺序','2');assert.equal(await selected(p).evaluate(n=>getComputedStyle(n).order),'2');
 await p.getByRole('button',{name:'下一页',exact:true}).click();await frame(p).locator('[data-ppte-id=g1]').click();await insert(p,'形状','矩形');assert.equal(await selected(p).evaluate(n=>n.parentElement?.getAttribute('data-ppte-id')),'grid');assert.equal(await frame(p).locator('[data-ppte-id=grid]').evaluate(n=>getComputedStyle(n).display),'grid');assert.notEqual(await selected(p).evaluate(n=>getComputedStyle(n).position),'absolute');await property(p,'容器内对齐','center');
 await frame(p).locator('[data-ppte-id=g1]').click();await property(p,'字号','24px');await frame(p).locator('[data-ppte-id=g2]').click({modifiers:['Shift']});assert.equal(await p.getByLabel('字号',{exact:true}).inputValue(),'混合');await property(p,'字号','22px');for(const id of ['g1','g2'])assert.equal(await frame(p).locator(`[data-ppte-id=${id}]`).evaluate(n=>getComputedStyle(n).fontSize),'22px');await p.getByRole('button',{name:'撤销',exact:true}).click();assert.equal(await frame(p).locator('[data-ppte-id=g1]').evaluate(n=>getComputedStyle(n).fontSize),'24px');assert.equal(await frame(p).locator('[data-ppte-id=g2]').evaluate(n=>getComputedStyle(n).fontSize),'16px');
 await p.getByRole('button',{name:'下一页',exact:true}).click();await frame(p).locator('[data-ppte-id=flow]').click();await insert(p,'形状','矩形');assert.equal(await selected(p).evaluate(n=>n.parentElement?.getAttribute('data-ppte-id')),'s3');assert.equal(await p.getByLabel('旋转',{exact:true}).count(),0);await property(p,'外边距','12px');assert.equal(await selected(p).evaluate(n=>getComputedStyle(n).marginTop),'12px');await p.screenshot({path:join(out,'flow.png')});
 }finally{await f.close();}});
test('UI02 acceptance 3: protection is bounded, command fixture/duplicate/delete history remains atomic and invalid actions leave content intact',async()=>{const f=await setup('protection');const p=f.p;try{
 await frame(p).locator('[data-ppte-id=locked]').click();const original=await frame(p).locator('[data-ppte-id=locked]').textContent();await property(p,'字号','99px');assert.match(await p.locator('#ppte-feedback').textContent()??'',/OBJECT_PROTECTED/);await insert(p,'形状','矩形');assert.equal(await frame(p).locator('[data-ppte-id=locked]').textContent(),original);const id=await selected(p).getAttribute('data-ppte-id');await p.getByRole('button',{name:'撤销',exact:true}).click();assert.equal(await frame(p).locator(`[data-ppte-id="${id}"]`).count(),0);await p.getByRole('button',{name:'重做',exact:true}).click();assert.equal(await frame(p).locator(`[data-ppte-id="${id}"]`).count(),1);
 await frame(p).locator(`[data-ppte-id="${id}"]`).click();await p.getByRole('button',{name:'复制对象',exact:true}).click();assert.equal(await frame(p).locator('[data-ppte-kind=shape]').count(),2);await p.getByRole('button',{name:'删除对象',exact:true}).click();assert.equal(await frame(p).locator('[data-ppte-kind=shape]').count(),1);await p.getByRole('button',{name:'撤销',exact:true}).click();assert.equal(await frame(p).locator('[data-ppte-kind=shape]').count(),2);await p.getByRole('button',{name:'重做',exact:true}).click();assert.equal(await frame(p).locator('[data-ppte-kind=shape]').count(),1);
 await frame(p).locator('[data-ppte-id=locked]').click();await p.getByRole('button',{name:'解除保护',exact:true}).click();assert.equal(await frame(p).locator('[data-ppte-id=locked]').getAttribute('contenteditable'),'true');await p.getByRole('button',{name:'撤销',exact:true}).click();assert.equal(await frame(p).locator('[data-ppte-id=locked]').getAttribute('contenteditable'),'false');
 const stable=await p.evaluate(()=>(window as any).PPTeHTML.content());const bad=p.waitForEvent('filechooser');await p.getByRole('button',{name:'插入图片',exact:true}).click();await(await bad).setFiles({name:'bad.png',mimeType:'image/png',buffer:Buffer.from('not an image')});await p.waitForFunction(()=>document.querySelector('#ppte-feedback')?.textContent?.includes('无法读取这张图片'));assert.equal(await p.evaluate(()=>(window as any).PPTeHTML.content()),stable);
 // Command boundary: locked ancestor, invalid grid size and overlapping selection are all-or-nothing.
 const result=await p.evaluate(()=>{const c=(window as any).PPTeEditor.commands;const before=c.doc.body.innerHTML;const depth=c.undoStack.length;const errors=[];try{c.insertObject('s1','table','text',100,2);}catch(e){errors.push(String(e));}try{c.style(['container','text'],'color','red');}catch(e){errors.push(String(e));}c.node('container').dataset.ppteLocked='true';try{c.insertObject('s1','rect','text');}catch(e){errors.push(String(e));}c.node('container').removeAttribute('data-ppte-locked');return {same:before===c.doc.body.innerHTML,depth:depth===c.undoStack.length,errors};});assert.equal(result.same,true);assert.equal(result.depth,true);assert.match(result.errors.join(' '),/TABLE_SIZE/);assert.match(result.errors.join(' '),/OVERLAPPING_SELECTION/);assert.match(result.errors.join(' '),/OBJECT_PROTECTED/);
 }finally{await f.close();}});
test('UI02 acceptance 4: one labeled SVG menu, keyboard navigation/escape/outside close and focus-safe properties', {skip:'F01 scope retirement: docs/focused-product/evidence/F01/TEST-MIGRATION.json; not a pass'}, async()=>{const f=await setup('focus');const p=f.p;try{
 const trigger=p.getByRole('button',{name:'插入',exact:true});await trigger.click();assert.equal(await trigger.getAttribute('aria-expanded'),'true');assert.equal(await p.getByRole('menuitem').count(),4);assert.equal(await p.locator('#ppte-insert-menu svg[aria-hidden=true]').count(),4);assert.equal(await p.getByRole('menuitem',{name:'文本框',exact:true}).evaluate(n=>getComputedStyle(n).color),'rgb(32, 36, 45)');assert.equal(await p.getByRole('menuitem',{name:'文本框',exact:true}).evaluate(n=>n===document.activeElement),true);await p.keyboard.press('ArrowDown');await p.keyboard.press('Enter');await p.keyboard.press('Escape');assert.equal(await trigger.evaluate(n=>n===document.activeElement),true);assert.equal(await trigger.getAttribute('aria-expanded'),'false');
 await trigger.click();await p.getByRole('menuitem',{name:'表格',exact:true}).click();await p.getByRole('menuitem',{name:'2 行 3 列',exact:true}).focus();assert.match(await p.locator('#ppte-insert-menu [role=status]').textContent()??'',/2 行 × 3 列/);await p.keyboard.press('ArrowDown');assert.match(await p.locator('#ppte-insert-menu [role=status]').textContent()??'',/3 行 × 3 列/);await p.keyboard.press('ArrowUp');await p.keyboard.press('Enter');assert.equal(await frame(p).locator('table tr').count(),2);assert.equal(await frame(p).locator('table tr').first().locator('td').count(),3);
 await trigger.click();await p.getByRole('menuitem',{name:'表格',exact:true}).click();await p.getByLabel('行数',{exact:true}).fill('6');await p.getByLabel('列数',{exact:true}).fill('7');await p.getByRole('menuitem',{name:'插入指定表格',exact:true}).click();assert.equal(await frame(p).locator('table').nth(1).locator('tr').count(),6);assert.equal(await frame(p).locator('table').nth(1).locator('tr').first().locator('td').count(),7);
 await trigger.click();await p.getByRole('button',{name:'页面设置',exact:true}).click();assert.equal(await trigger.getAttribute('aria-expanded'),'false');
 await trigger.focus();await p.keyboard.press('t');assert.equal(await frame(p).locator('[data-ppte-kind=text]').count(),1);await selected(p).fill('t 不触发插入');await selected(p).press('t');assert.equal(await frame(p).locator('[data-ppte-kind=text]').count(),1);await property(p,'字号','24px');assert.match(await selected(p).textContent()??'',/t/);await p.getByLabel('字号',{exact:true}).focus();await p.keyboard.press('t');assert.equal(await frame(p).locator('[data-ppte-kind=text]').count(),1);
 await trigger.focus();await p.keyboard.press('Enter');assert.match(await p.getByRole('menuitem',{name:'文本框',exact:true}).evaluate(n=>getComputedStyle(n).outlineStyle),/solid/);await p.screenshot({path:join(out,'menu-focus.png')});await p.keyboard.press('Escape');await p.getByRole('button',{name:'阅读',exact:true}).click();await p.keyboard.press('t');assert.equal(await frame(p).locator('[data-ppte-kind=text]').count(),1);
 }finally{await f.close();}});
