import { canonicalHash } from '../../canonical-json/src/index.js'
import { withErrorSemantics } from '../../schema/src/errors.js'
import type {
  ChangeContract,
  Element,
  Operation,
  OperationKind,
  PpteDocument,
  Precondition,
  RichTextDocument,
  ScopePermission,
  Transaction,
  TransactionScope,
  ValidationIssue,
} from '../../schema/src/index.js'
import type { StructuralDiff } from '../../schema/src/index.js'

export interface OperationImpact {
  kind: OperationKind
  slideIds: string[]
  elementIds: string[]
  semanticKeys: string[]
  paths: string[]
  permissions: ScopePermission[]
  inserts: number
  deletes: number
  replacedAssets: number
}

export interface ChangeContractEnforcementOptions {
  /** Only the inverse generated by PpteSession.undo may bypass a just-created lock. */
  allowSystemInversePolicy?: boolean
}

/** The measured mutation surface used by contracts and Agent tool responses. */
export interface MutationBudget {
  changedSlides: number
  changedElements: number
  insertedElements: number
  deletedElements: number
  replacedAssets: number
  changedFacts: number
  changedSources: number
  changedThemeTokens: number
  changedStylePresets: number
}

export function measureMutationBudget(diff: StructuralDiff): MutationBudget {
  return { ...diff.mutationSummary }
}

export function contentOnlyContract(elementId: string): ChangeContract {
  return { allowedOperationKinds: ['text.replaceContent'], allowedElementIds: [elementId], ...zeroBudget(1), preserve: { geometry: 'preserve', style: 'preserve', asset: 'preserve', semanticIdentity: 'preserve', readingOrder: 'preserve', facts: 'preserve' }, requireConfirmation: false, userIntentSummary: 'Only replace selected text content.' }
}

export function componentPropsContract(elementId: string, requireConfirmation = false): ChangeContract {
  return { allowedOperationKinds: ['component.updateProps'], allowedElementIds: [elementId], ...zeroBudget(1), preserve: { geometry: 'preserve', style: 'preserve', asset: 'preserve', semanticIdentity: 'preserve', readingOrder: 'preserve', facts: 'preserve' }, requireConfirmation, userIntentSummary: 'Only update the selected Widget properties.' }
}

export function cropOnlyContract(elementId: string, requireConfirmation = false): ChangeContract {
  return { allowedOperationKinds: ['image.setCrop'], allowedElementIds: [elementId], ...zeroBudget(1), preserve: { content: 'preserve', data: 'preserve', style: 'preserve', geometry: 'preserve', semanticIdentity: 'preserve', readingOrder: 'preserve', facts: 'preserve' }, requireConfirmation, userIntentSummary: 'Only update the selected Image crop.' }
}

export function chartDataOnlyContract(elementId: string, requireConfirmation = false): ChangeContract {
  return { allowedOperationKinds: ['chart.replaceData'], allowedElementIds: [elementId], ...zeroBudget(1), preserve: { content: 'allow', style: 'preserve', geometry: 'preserve', asset: 'preserve', semanticIdentity: 'preserve', readingOrder: 'preserve', facts: 'preserve' }, requireConfirmation, userIntentSummary: 'Only replace the selected Chart data.' }
}

export function geometryOnlyContract(elementIds: string[], requireConfirmation = true): ChangeContract {
  return { allowedOperationKinds: ['element.move', 'element.resize', 'layout.align', 'layout.distribute'], allowedElementIds: elementIds, ...zeroBudget(elementIds.length), preserve: { content: 'preserve', data: 'preserve', style: 'preserve', asset: 'preserve', semanticIdentity: 'preserve', readingOrder: 'preserve', facts: 'preserve' }, requireConfirmation, userIntentSummary: 'Change geometry while preserving semantic content and style.' }
}

export function styleOnlyContract(elementIds: string[], requireConfirmation = true): ChangeContract {
  return { allowedOperationKinds: ['element.setStyleRef', 'element.updateStyleOverrides', 'element.clearStyleOverrides', 'theme.updatePreset'], allowedElementIds: elementIds, ...zeroBudget(elementIds.length), maxChangedStylePresets: 1, preserve: { content: 'preserve', data: 'preserve', geometry: 'preserve', asset: 'preserve', semanticIdentity: 'preserve', readingOrder: 'preserve', facts: 'preserve' }, requireConfirmation, userIntentSummary: 'Change style within the selected scope.' }
}

export function replaceAssetContract(elementId: string, requireConfirmation = true): ChangeContract {
  return { allowedOperationKinds: ['image.replaceAsset', 'image.setCrop', 'image.setFocalPoint'], allowedElementIds: [elementId], ...zeroBudget(1), maxReplacedAssets: 1, preserve: { content: 'preserve', data: 'preserve', style: 'preserve', geometry: 'preserve', semanticIdentity: 'preserve', readingOrder: 'preserve', facts: 'preserve' }, requireConfirmation, userIntentSummary: 'Replace one Image Asset without changing its semantic placement.' }
}

export function fullWithinScopeContract(allowedOperationKinds: OperationKind[], maxChangedElements = Number.MAX_SAFE_INTEGER): ChangeContract {
  return { allowedOperationKinds, maxChangedSlides: Number.MAX_SAFE_INTEGER, maxChangedElements, maxInsertedElements: Number.MAX_SAFE_INTEGER, maxDeletedElements: Number.MAX_SAFE_INTEGER, maxReplacedAssets: Number.MAX_SAFE_INTEGER, maxChangedFacts: Number.MAX_SAFE_INTEGER, maxChangedSources: Number.MAX_SAFE_INTEGER, maxChangedThemeTokens: Number.MAX_SAFE_INTEGER, maxChangedStylePresets: Number.MAX_SAFE_INTEGER, requireConfirmation: true, userIntentSummary: 'Allow the declared operations within the granted Scope.' }
}

function zeroBudget(maxChangedElements: number): Pick<ChangeContract, 'maxChangedSlides' | 'maxChangedElements' | 'maxInsertedElements' | 'maxDeletedElements' | 'maxReplacedAssets' | 'maxChangedFacts' | 'maxChangedSources' | 'maxChangedThemeTokens' | 'maxChangedStylePresets'> {
  return { maxChangedSlides: 1, maxChangedElements: Math.max(0, maxChangedElements), maxInsertedElements: 0, maxDeletedElements: 0, maxReplacedAssets: 0, maxChangedFacts: 0, maxChangedSources: 0, maxChangedThemeTokens: 0, maxChangedStylePresets: 0 }
}

export function analyzeOperation(document: PpteDocument, operation: Operation): OperationImpact {
  const slideIds = new Set<string>()
  const elementIds = new Set<string>()
  const semanticKeys = new Set<string>()
  const paths = new Set<string>()
  const permissions = new Set<ScopePermission>()
  let inserts = 0
  let deletes = 0
  let replacedAssets = 0

  const addElement = (slideId: string, elementId: string, path = `/slides/${pointer(slideId)}/elements/${pointer(elementId)}`, semanticKey?: string) => {
    slideIds.add(slideId)
    elementIds.add(elementId)
    paths.add(path)
    const element = document.slides[slideId]?.elements[elementId]
    if (element?.semanticKey ?? semanticKey) semanticKeys.add((element?.semanticKey ?? semanticKey) as string)
  }
  const addGroupMembers = (slideId: string, groupId: string) => {
    slideIds.add(slideId)
    for (const memberId of document.slides[slideId]?.groups?.[groupId]?.memberIds ?? []) addElement(slideId, memberId)
  }

  switch (operation.kind) {
    case 'document.updateMetadata':
      permissions.add('structure')
      paths.add('/metadata')
      break
    case 'theme.replace':
      permissions.add('theme')
      paths.add('/theme')
      break
    case 'theme.setToken':
      permissions.add('theme')
      paths.add(`/theme/tokens/${pointer(operation.category)}/${pointer(operation.token)}`)
      break
    case 'theme.updatePreset':
      permissions.add('theme')
      paths.add(`/theme/presets/${pointer(operation.category)}/${pointer(operation.presetId)}`)
      break
    case 'slide.insert':
      permissions.add('structure')
      slideIds.add(operation.slide.id)
      paths.add('/slideOrder')
      inserts += Object.keys(operation.slide.elements).length
      break
    case 'slide.duplicate': {
      permissions.add('structure')
      slideIds.add(operation.sourceSlideId)
      slideIds.add(operation.newSlideId)
      paths.add('/slideOrder')
      paths.add(`/slides/${pointer(operation.newSlideId)}`)
      inserts += Object.keys(document.slides[operation.sourceSlideId]?.elements ?? {}).length
      break
    }
    case 'slide.delete':
      permissions.add('structure')
      slideIds.add(operation.slideId)
      paths.add(`/slides/${pointer(operation.slideId)}`)
      deletes += Object.keys(document.slides[operation.slideId]?.elements ?? {}).length
      break
    case 'slide.move':
      permissions.add('structure')
      slideIds.add(operation.slideId)
      paths.add('/slideOrder')
      break
    case 'slide.update':
      slideIds.add(operation.slideId)
      for (const key of Object.keys(operation.patch)) {
        paths.add(`/slides/${pointer(operation.slideId)}/${pointer(key)}`)
        permissions.add(key === 'notes' ? 'notes' : 'structure')
      }
      break
    case 'slide.setNotes':
      permissions.add('notes')
      slideIds.add(operation.slideId)
      paths.add(`/slides/${pointer(operation.slideId)}/notes`)
      break
    case 'slide.setTransition':
      permissions.add('animation')
      slideIds.add(operation.slideId)
      paths.add(`/slides/${pointer(operation.slideId)}/transition`)
      break
    case 'slide.setReadingOrder':
      permissions.add('structure')
      slideIds.add(operation.slideId)
      paths.add(`/slides/${pointer(operation.slideId)}/readingOrder`)
      break
    case 'slide.setProtectedAnchors':
      permissions.add('structure')
      slideIds.add(operation.slideId)
      paths.add(`/slides/${pointer(operation.slideId)}/protectedAnchors`)
      break
    case 'element.insert':
      permissions.add('structure')
      addElement(operation.slideId, operation.element.id, `/slides/${pointer(operation.slideId)}/elements/${pointer(operation.element.id)}`, operation.element.semanticKey)
      inserts += 1
      break
    case 'element.delete':
      permissions.add('structure')
      addElement(operation.slideId, operation.elementId)
      deletes += 1
      break
    case 'element.duplicate':
      permissions.add('structure')
      addElement(operation.slideId, operation.sourceElementId)
      addElement(operation.slideId, operation.newElementId, `/slides/${pointer(operation.slideId)}/elements/${pointer(operation.newElementId)}`)
      inserts += 1
      break
    case 'element.move':
      permissions.add('geometry')
      addElement(operation.slideId, operation.elementId, `/slides/${pointer(operation.slideId)}/elements/${pointer(operation.elementId)}/frame`)
      break
    case 'element.resize':
      permissions.add('geometry')
      addElement(operation.slideId, operation.elementId, `/slides/${pointer(operation.slideId)}/elements/${pointer(operation.elementId)}/frame`)
      break
    case 'element.rotate':
      permissions.add('geometry')
      addElement(operation.slideId, operation.elementId, `/slides/${pointer(operation.slideId)}/elements/${pointer(operation.elementId)}/rotationDeg`)
      break
    case 'element.reorder':
      permissions.add('structure')
      addElement(operation.slideId, operation.elementId, `/slides/${pointer(operation.slideId)}/rootOrder`)
      break
    case 'element.setVisibility':
      permissions.add('structure')
      addElement(operation.slideId, operation.elementId, `/slides/${pointer(operation.slideId)}/elements/${pointer(operation.elementId)}/visible`)
      break
    case 'element.setLocked':
      permissions.add('structure')
      addElement(operation.slideId, operation.elementId, `/slides/${pointer(operation.slideId)}/elements/${pointer(operation.elementId)}/locked`)
      break
    case 'element.setAppearStep':
      permissions.add('animation')
      addElement(operation.slideId, operation.elementId, `/slides/${pointer(operation.slideId)}/elements/${pointer(operation.elementId)}/appearStep`)
      break
    case 'element.setAnimation':
      permissions.add('animation')
      addElement(operation.slideId, operation.elementId, `/slides/${pointer(operation.slideId)}/elements/${pointer(operation.elementId)}/animation`)
      break
    case 'element.setEditPolicy':
      permissions.add('structure')
      addElement(operation.slideId, operation.elementId, `/slides/${pointer(operation.slideId)}/elements/${pointer(operation.elementId)}/editPolicy`)
      break
    case 'element.setSemanticKey':
      permissions.add('structure')
      addElement(operation.slideId, operation.elementId, `/slides/${pointer(operation.slideId)}/elements/${pointer(operation.elementId)}/semanticKey`)
      break
    case 'element.setSemanticRefs':
      permissions.add('content')
      addElement(operation.slideId, operation.elementId, `/slides/${pointer(operation.slideId)}/elements/${pointer(operation.elementId)}/semanticRefs`)
      break
    case 'element.setStyleRef':
      permissions.add('style')
      addElement(operation.slideId, operation.elementId, `/slides/${pointer(operation.slideId)}/elements/${pointer(operation.elementId)}/style/styleRef`)
      break
    case 'element.updateStyleOverrides':
      permissions.add('style')
      addElement(operation.slideId, operation.elementId, `/slides/${pointer(operation.slideId)}/elements/${pointer(operation.elementId)}/style/overrides`)
      break
    case 'element.clearStyleOverrides':
      permissions.add('style')
      addElement(operation.slideId, operation.elementId, `/slides/${pointer(operation.slideId)}/elements/${pointer(operation.elementId)}/style/overrides`)
      break
    case 'text.replaceContent':
      permissions.add('content')
      addElement(operation.slideId, operation.elementId, `/slides/${pointer(operation.slideId)}/elements/${pointer(operation.elementId)}/content`)
      break
    case 'text.updateStyle':
      permissions.add('style')
      addElement(operation.slideId, operation.elementId, `/slides/${pointer(operation.slideId)}/elements/${pointer(operation.elementId)}/paragraphStyle`)
      if (operation.boxStyle !== undefined || operation.unsetBoxStyle) paths.add(`/slides/${pointer(operation.slideId)}/elements/${pointer(operation.elementId)}/boxStyle`)
      break
    case 'text.setOverflowPolicy':
      permissions.add('style')
      addElement(operation.slideId, operation.elementId, `/slides/${pointer(operation.slideId)}/elements/${pointer(operation.elementId)}/overflowPolicy`)
      break
    case 'text.fitByReducingFont':
      permissions.add('style')
      addElement(operation.slideId, operation.elementId, `/slides/${pointer(operation.slideId)}/elements/${pointer(operation.elementId)}/style/overrides/fontSize`)
      break
    case 'text.resizeBox':
      permissions.add('geometry')
      addElement(operation.slideId, operation.elementId, `/slides/${pointer(operation.slideId)}/elements/${pointer(operation.elementId)}/frame`)
      break
    case 'image.replaceAsset':
      permissions.add('assets')
      addElement(operation.slideId, operation.elementId, `/slides/${pointer(operation.slideId)}/elements/${pointer(operation.elementId)}/assetId`)
      replacedAssets += 1
      break
    case 'image.setCrop':
      permissions.add('assets')
      addElement(operation.slideId, operation.elementId, `/slides/${pointer(operation.slideId)}/elements/${pointer(operation.elementId)}/crop`)
      break
    case 'image.setFocalPoint':
      permissions.add('assets')
      addElement(operation.slideId, operation.elementId, `/slides/${pointer(operation.slideId)}/elements/${pointer(operation.elementId)}/focalPoint`)
      break
    case 'asset.upsert':
      permissions.add('assets')
      paths.add(`/assets/${pointer(operation.asset.id)}`)
      break
    case 'font.upsert':
      permissions.add('assets')
      paths.add(`/fonts/${pointer(operation.font.id)}`)
      break
    case 'shape.updateStyle':
      permissions.add('style')
      addElement(operation.slideId, operation.elementId, `/slides/${pointer(operation.slideId)}/elements/${pointer(operation.elementId)}/style`)
      break
    case 'chart.replaceData':
      permissions.add('content')
      addElement(operation.slideId, operation.elementId, `/slides/${pointer(operation.slideId)}/elements/${pointer(operation.elementId)}/data`)
      break
    case 'chart.updateEncoding':
      permissions.add('content')
      addElement(operation.slideId, operation.elementId, `/slides/${pointer(operation.slideId)}/elements/${pointer(operation.elementId)}/encoding`)
      break
    case 'chart.updateOptions':
      permissions.add('content')
      addElement(operation.slideId, operation.elementId, `/slides/${pointer(operation.slideId)}/elements/${pointer(operation.elementId)}/options`)
      break
    case 'chart.updateStyle':
      permissions.add('style')
      addElement(operation.slideId, operation.elementId, `/slides/${pointer(operation.slideId)}/elements/${pointer(operation.elementId)}/style/overrides`)
      break
    case 'component.updateProps':
      permissions.add('content')
      addElement(operation.slideId, operation.elementId)
      break
    case 'group.create':
      permissions.add('structure')
      slideIds.add(operation.slideId)
      paths.add(`/slides/${pointer(operation.slideId)}/groups/${pointer(operation.group.id)}`)
      for (const elementId of operation.group.memberIds) addElement(operation.slideId, elementId)
      break
    case 'group.delete':
      permissions.add('structure')
      slideIds.add(operation.slideId)
      paths.add(`/slides/${pointer(operation.slideId)}/groups/${pointer(operation.groupId)}`)
      addGroupMembers(operation.slideId, operation.groupId)
      break
    case 'group.addMembers':
    case 'group.removeMembers':
      permissions.add('structure')
      slideIds.add(operation.slideId)
      paths.add(`/slides/${pointer(operation.slideId)}/groups/${pointer(operation.groupId)}/memberIds`)
      for (const elementId of operation.elementIds) addElement(operation.slideId, elementId)
      break
    case 'group.move':
      permissions.add('geometry')
      addGroupMembers(operation.slideId, operation.groupId)
      break
    case 'group.resize':
      permissions.add('geometry')
      addGroupMembers(operation.slideId, operation.groupId)
      if (operation.scaleTextStyle) {
        permissions.add('style')
        for (const elementId of document.slides[operation.slideId]?.groups?.[operation.groupId]?.memberIds ?? []) {
          const element = document.slides[operation.slideId]?.elements[elementId]
          if (element?.type === 'text') paths.add(`/slides/${pointer(operation.slideId)}/elements/${pointer(elementId)}/style/overrides/fontSize`)
        }
      }
      break
    case 'group.rotate':
      permissions.add('geometry')
      addGroupMembers(operation.slideId, operation.groupId)
      break
    case 'fact.upsert':
      permissions.add('facts')
      paths.add(`/facts/${pointer(operation.fact.id)}`)
      break
    case 'fact.delete':
      permissions.add('facts')
      paths.add(`/facts/${pointer(operation.factId)}`)
      break
    case 'fact.syncReferences':
      permissions.add('facts')
      permissions.add('content')
      paths.add(`/facts/${pointer(operation.factId)}`)
      for (const elementId of operation.targetElementIds) {
        for (const slideId of document.slideOrder) {
          const element = document.slides[slideId].elements[elementId]
          if (!element) continue
          const field = element.type === 'chart' ? 'data' : 'content'
          addElement(slideId, elementId, `/slides/${pointer(slideId)}/elements/${pointer(elementId)}/${field}`)
        }
      }
      break
    case 'source.upsert':
      permissions.add('sources')
      paths.add(`/sources/${pointer(operation.source.id)}`)
      break
    case 'source.delete':
      permissions.add('sources')
      paths.add(`/sources/${pointer(operation.sourceId)}`)
      break
    case 'layout.align':
    case 'layout.distribute':
      permissions.add('geometry')
      slideIds.add(operation.slideId)
      for (const elementId of operation.elementIds) addElement(operation.slideId, elementId)
      break
  }
  return { kind: operation.kind, slideIds: [...slideIds], elementIds: [...elementIds], semanticKeys: [...semanticKeys], paths: [...paths], permissions: [...permissions], inserts, deletes, replacedAssets }
}

export function enforceChangeContract(
  before: PpteDocument,
  after: PpteDocument,
  transaction: Transaction,
  diff: StructuralDiff,
  options: ChangeContractEnforcementOptions = {},
): ValidationIssue[] {
  const issues: ValidationIssue[] = []
  const contract = transaction.changeContract
  const scope = transaction.scope
  const impacts = transaction.operations.map((operation) => analyzeOperation(before, operation))
  const allElements = new Set(impacts.flatMap((impact) => impact.elementIds))
  const allSlides = new Set(impacts.flatMap((impact) => impact.slideIds))
  const paths = new Set(impacts.flatMap((impact) => impact.paths))
  const permissions = new Set(impacts.flatMap((impact) => impact.permissions))
  const actualTargets = actualElementTargets(before, after, diff)

  for (const impact of impacts) {
    if (contract.allowedOperationKinds && !contract.allowedOperationKinds.includes(impact.kind)) {
      issues.push(issue('CHANGE_KIND_NOT_ALLOWED', `Operation ${impact.kind} is outside the Change Contract.`))
    }
    for (const permission of impact.permissions) {
      if (!scope.permissions.includes(permission)) issues.push(issue('SCOPE_VIOLATION', `Operation ${impact.kind} requires permission ${permission}.`))
    }
    if (impact.inserts > 0 && scope.allowInsert !== true) issues.push(issue('SCOPE_VIOLATION', 'The transaction attempts to insert an element but insertion is not granted.'))
    if (impact.deletes > 0 && scope.allowDelete !== true) issues.push(issue('SCOPE_VIOLATION', 'The transaction attempts to delete an element but deletion is not granted.'))
    for (const slideId of impact.slideIds) {
      if (scope.slideIds && !scope.slideIds.includes(slideId)) issues.push(issue('SCOPE_VIOLATION', `Slide ${slideId} is outside the transaction scope.`, { slideId }))
    }
    for (const elementId of impact.elementIds) {
      const slideId = findElementSlide(before, elementId)
      if (scope.elementIds && !scope.elementIds.includes(elementId)) issues.push(issue('SCOPE_VIOLATION', `Element ${elementId} is outside the transaction scope.`, { elementId, slideId }))
      if (contract.allowedElementIds && !contract.allowedElementIds.includes(elementId)) issues.push(issue('SCOPE_VIOLATION', `Element ${elementId} is outside the Change Contract.`, { elementId, slideId }))
    }
    for (const semanticKey of impact.semanticKeys) {
      if (scope.semanticKeys && !scope.semanticKeys.includes(semanticKey)) issues.push(issue('SCOPE_VIOLATION', `semanticKey ${semanticKey} is outside the transaction scope.`, { semanticKey }))
      if (contract.allowedSemanticKeys && !contract.allowedSemanticKeys.includes(semanticKey)) issues.push(issue('SCOPE_VIOLATION', `semanticKey ${semanticKey} is outside the Change Contract.`, { semanticKey }))
    }
  }
  for (const { slideId, elementId } of actualTargets) {
    const element = after.slides[slideId]?.elements[elementId] ?? before.slides[slideId]?.elements[elementId]
    const semanticKey = element?.semanticKey
    if (scope.slideIds && !scope.slideIds.includes(slideId)) issues.push(issue('SCOPE_VIOLATION', `Actual Diff changed slide ${slideId} outside the transaction scope.`, { slideId }))
    if (scope.elementIds && !scope.elementIds.includes(elementId)) issues.push(issue('SCOPE_VIOLATION', `Actual Diff changed element ${elementId} outside the transaction scope.`, { elementId, slideId }))
    if (contract.allowedElementIds && !contract.allowedElementIds.includes(elementId)) issues.push(issue('SCOPE_VIOLATION', `Actual Diff changed element ${elementId} outside the Change Contract.`, { elementId, slideId }))
    if (semanticKey && scope.semanticKeys && !scope.semanticKeys.includes(semanticKey)) issues.push(issue('SCOPE_VIOLATION', `Actual Diff changed semanticKey ${semanticKey} outside the transaction scope.`, { semanticKey, slideId, elementId }))
    if (semanticKey && contract.allowedSemanticKeys && !contract.allowedSemanticKeys.includes(semanticKey)) issues.push(issue('SCOPE_VIOLATION', `Actual Diff changed semanticKey ${semanticKey} outside the Change Contract.`, { semanticKey, slideId, elementId }))
  }
  if (contract.allowedPaths) {
    for (const path of [...paths, ...diff.changedPaths]) if (!contract.allowedPaths.some((allowed) => pathMatches(path, allowed))) issues.push(issue('CHANGE_PATH_NOT_ALLOWED', `Path ${path} is outside the Change Contract.`))
  }
  if (contract.maxChangedSlides !== undefined && diff.mutationSummary.changedSlides > contract.maxChangedSlides) issues.push(issue('MUTATION_BUDGET_EXCEEDED', `Changed ${diff.mutationSummary.changedSlides} slides; budget is ${contract.maxChangedSlides}.`))
  if (contract.maxChangedElements !== undefined && diff.mutationSummary.changedElements > contract.maxChangedElements) issues.push(issue('MUTATION_BUDGET_EXCEEDED', `Changed ${diff.mutationSummary.changedElements} elements; budget is ${contract.maxChangedElements}.`))
  if (contract.maxInsertedElements !== undefined && diff.mutationSummary.insertedElements > contract.maxInsertedElements) issues.push(issue('MUTATION_BUDGET_EXCEEDED', `Inserted ${diff.mutationSummary.insertedElements} elements; budget is ${contract.maxInsertedElements}.`))
  if (contract.maxDeletedElements !== undefined && diff.mutationSummary.deletedElements > contract.maxDeletedElements) issues.push(issue('MUTATION_BUDGET_EXCEEDED', `Deleted ${diff.mutationSummary.deletedElements} elements; budget is ${contract.maxDeletedElements}.`))
  if (contract.maxReplacedAssets !== undefined && diff.mutationSummary.replacedAssets > contract.maxReplacedAssets) issues.push(issue('MUTATION_BUDGET_EXCEEDED', `Replaced ${diff.mutationSummary.replacedAssets} assets; budget is ${contract.maxReplacedAssets}.`))
  if (contract.maxChangedFacts !== undefined && diff.mutationSummary.changedFacts > contract.maxChangedFacts) issues.push(issue('MUTATION_BUDGET_EXCEEDED', `Changed ${diff.mutationSummary.changedFacts} facts; budget is ${contract.maxChangedFacts}.`, { path: '/facts' }))
  if (contract.maxChangedSources !== undefined && diff.mutationSummary.changedSources > contract.maxChangedSources) issues.push(issue('MUTATION_BUDGET_EXCEEDED', `Changed ${diff.mutationSummary.changedSources} sources; budget is ${contract.maxChangedSources}.`, { path: '/sources' }))
  if (contract.maxChangedThemeTokens !== undefined && diff.mutationSummary.changedThemeTokens > contract.maxChangedThemeTokens) issues.push(issue('MUTATION_BUDGET_EXCEEDED', `Changed ${diff.mutationSummary.changedThemeTokens} theme tokens; budget is ${contract.maxChangedThemeTokens}.`, { path: '/theme/tokens' }))
  if (contract.maxChangedStylePresets !== undefined && diff.mutationSummary.changedStylePresets > contract.maxChangedStylePresets) issues.push(issue('MUTATION_BUDGET_EXCEEDED', `Changed ${diff.mutationSummary.changedStylePresets} style presets; budget is ${contract.maxChangedStylePresets}.`, { path: '/theme/presets' }))

  for (const operation of transaction.operations) {
    const policyIssues = checkEditPolicy(before, operation, transaction.actor.type, options)
    issues.push(...policyIssues)
  }
  if (!options.allowSystemInversePolicy || transaction.actor.type !== 'system') issues.push(...checkActualEditPolicy(before, after, transaction, diff))
  issues.push(...checkInvariants(before, after, contract))
  issues.push(...checkProtectedAnchors(before, after, contract))
  return dedupeIssues(issues)
}

export function checkPreconditions(document: PpteDocument, revision: string, operations: Operation[]): ValidationIssue[] {
  const issues: ValidationIssue[] = []
  for (const operation of operations) {
    for (const precondition of operation.preconditions ?? []) {
      const failure = checkPrecondition(document, revision, precondition)
      if (failure) issues.push(failure)
    }
  }
  return issues
}

export function checkTransactionScope(scope: TransactionScope): ValidationIssue[] {
  const issues: ValidationIssue[] = []
  if (!scope || typeof scope !== 'object') return [issue('SCOPE_VIOLATION', 'Transaction scope must be an object.')]
  if (!Array.isArray(scope.permissions) || scope.permissions.length === 0) issues.push(issue('SCOPE_VIOLATION', 'A transaction must grant at least one permission.'))
  if (Array.isArray(scope.permissions) && new Set(scope.permissions).size !== scope.permissions.length) issues.push(issue('SCOPE_VIOLATION', 'Transaction permissions must be unique.'))
  if (scope.kind === 'selection' && !scope.elementIds?.length && !scope.semanticKeys?.length) issues.push(issue('SCOPE_VIOLATION', 'Selection scope must name elementIds or semanticKeys.'))
  if (scope.kind === 'slide' && !scope.slideIds?.length) issues.push(issue('SCOPE_VIOLATION', 'Slide scope must name at least one slideId.'))
  if (scope.elementIds && new Set(scope.elementIds).size !== scope.elementIds.length) issues.push(issue('SCOPE_VIOLATION', 'Scope elementIds must be unique.'))
  if (scope.semanticKeys && new Set(scope.semanticKeys).size !== scope.semanticKeys.length) issues.push(issue('SCOPE_VIOLATION', 'Scope semanticKeys must be unique.'))
  if (scope.slideIds && new Set(scope.slideIds).size !== scope.slideIds.length) issues.push(issue('SCOPE_VIOLATION', 'Scope slideIds must be unique.'))
  return issues
}

function checkPrecondition(document: PpteDocument, revision: string, precondition: Precondition): ValidationIssue | undefined {
  switch (precondition.kind) {
    case 'revision-equals':
      return revision !== precondition.revision ? issue('REVISION_CONFLICT', `Precondition expected ${precondition.revision}, current revision is ${revision}.`) : undefined
    case 'slide-exists':
      return document.slides[precondition.slideId] ? undefined : issue('SCHEMA_INVALID', `Precondition slide does not exist: ${precondition.slideId}.`, { slideId: precondition.slideId })
    case 'element-exists':
      return document.slides[precondition.slideId]?.elements[precondition.elementId] ? undefined : issue('SCHEMA_INVALID', `Precondition element does not exist: ${precondition.elementId}.`, { slideId: precondition.slideId, elementId: precondition.elementId })
    case 'semantic-key-resolves': {
      const matches = Object.values(document.slides[precondition.slideId]?.elements ?? {}).filter((element) => element.semanticKey === precondition.semanticKey)
      const found = matches.length === 1 ? matches[0] : undefined
      if (!found || (precondition.elementId && found.id !== precondition.elementId)) return issue('SEMANTIC_LINEAGE_AMBIGUOUS', `Precondition semanticKey does not resolve uniquely: ${precondition.semanticKey}.`, { slideId: precondition.slideId, semanticKey: precondition.semanticKey })
      return undefined
    }
    case 'fact-exists':
      return document.facts?.[precondition.factId] ? undefined : issue('FACT_REFERENCE_MISSING', `Precondition fact does not exist: ${precondition.factId}.`, { factId: precondition.factId })
    case 'path-value-equals': {
      const actual = readPointer(document, precondition.path)
      return canonicalHash(actual) === canonicalHash(precondition.value) ? undefined : issue('REVISION_CONFLICT', `Precondition value does not match at ${precondition.path}.`, { path: precondition.path })
    }
    case 'path-hash-equals': {
      const actual = readPointer(document, precondition.path)
      return canonicalHash(actual) === precondition.hash ? undefined : issue('REVISION_CONFLICT', `Precondition hash does not match at ${precondition.path}.`, { path: precondition.path })
    }
  }
}

function checkEditPolicy(document: PpteDocument, operation: Operation, actorType: Transaction['actor']['type'], options: ChangeContractEnforcementOptions = {}): ValidationIssue[] {
  const issues: ValidationIssue[] = []
  if (options.allowSystemInversePolicy && actorType === 'system') return issues
  if (operation.kind.startsWith('group.') && operation.kind !== 'group.create') {
    const slideId = 'slideId' in operation ? operation.slideId : undefined
    const groupId = 'groupId' in operation ? operation.groupId : undefined
    const group = slideId && groupId ? document.slides[slideId]?.groups?.[groupId] : undefined
    if (group?.locked || group?.editPolicy?.mode === 'locked') issues.push(issue('EDIT_POLICY_VIOLATION', `Group ${groupId} is locked.`, { slideId, path: `/slides/${pointer(slideId ?? '')}/groups/${pointer(groupId ?? '')}` }))
    if (actorType === 'agent' && group?.editPolicy?.agentEditable === false) issues.push(issue('EDIT_POLICY_VIOLATION', `Agent editing is disabled for group ${groupId}.`, { slideId, path: `/slides/${pointer(slideId ?? '')}/groups/${pointer(groupId ?? '')}` }))
  }
  for (const elementId of analyzeOperation(document, operation).elementIds) {
    const slideId = findElementSlide(document, elementId)
    const element = slideId ? document.slides[slideId].elements[elementId] : undefined
    if (!slideId || !element) continue
    if (element.locked || element.editPolicy?.mode === 'locked') issues.push(issue('EDIT_POLICY_VIOLATION', `Element ${elementId} is locked.`, { slideId, elementId }))
    if (actorType === 'agent' && element.editPolicy?.agentEditable === false) issues.push(issue('EDIT_POLICY_VIOLATION', `Agent editing is disabled for ${elementId}.`, { slideId, elementId }))
    if (element.editPolicy?.mode === 'replace' && operation.kind !== 'image.replaceAsset') issues.push(issue('EDIT_POLICY_VIOLATION', `Only explicit asset replacement is allowed for replace-only element ${elementId}.`, { slideId, elementId }))
    if (element.editPolicy?.lockedFields?.some((lockedPath) => analyzeOperation(document, operation).paths.some((path) => path === `/slides/${pointer(slideId)}/elements/${pointer(elementId)}${lockedPath}` || path.startsWith(`/slides/${pointer(slideId)}/elements/${pointer(elementId)}${lockedPath}/`)))) issues.push(issue('EDIT_POLICY_VIOLATION', `Operation ${operation.kind} touches a locked field on ${elementId}.`, { slideId, elementId }))
  }
  return issues
}

function checkActualEditPolicy(before: PpteDocument, after: PpteDocument, transaction: Transaction, diff: StructuralDiff): ValidationIssue[] {
  const issues: ValidationIssue[] = []
  for (const target of actualElementTargets(before, after, diff)) {
    const beforeElement = before.slides[target.slideId]?.elements[target.elementId]
    const element = beforeElement ?? after.slides[target.slideId]?.elements[target.elementId]
    if (!element) continue
    if (element.locked || element.editPolicy?.mode === 'locked') issues.push(issue('EDIT_POLICY_VIOLATION', `Element ${target.elementId} is locked.`, { slideId: target.slideId, elementId: target.elementId, semanticKey: element.semanticKey }))
    if (transaction.actor.type === 'agent' && element.editPolicy?.agentEditable === false) issues.push(issue('EDIT_POLICY_VIOLATION', `Agent editing is disabled for ${target.elementId}.`, { slideId: target.slideId, elementId: target.elementId, semanticKey: element.semanticKey }))
    if (element.editPolicy?.mode === 'replace' && transaction.operations.some((operation) => operation.kind === 'slide.update')) issues.push(issue('EDIT_POLICY_VIOLATION', `Only explicit asset replacement is allowed for replace-only element ${target.elementId}.`, { slideId: target.slideId, elementId: target.elementId, semanticKey: element.semanticKey }))
  }
  return issues
}

function actualElementTargets(before: PpteDocument, after: PpteDocument, diff: StructuralDiff): Array<{ slideId: string; elementId: string }> {
  const targets = new Map<string, { slideId: string; elementId: string }>()
  const add = (slideId: string, elementId: string) => targets.set(`${slideId}:${elementId}`, { slideId, elementId })
  for (const item of diff.addedElements) add(item.slideId, item.elementId)
  for (const item of diff.removedElements) add(item.slideId, item.elementId)
  for (const item of diff.replacedElements) { add(item.slideId, item.beforeElementId); add(item.slideId, item.afterElementId) }
  for (const path of diff.changedPaths) {
    const tokens = path.split('/').slice(1).map(unescapePointer)
    if (tokens[0] === 'slides' && tokens[2] === 'elements' && tokens[1] && tokens[3]) add(tokens[1], tokens[3])
  }
  // A replacement can be represented by a root-level add/remove path, so the
  // structural arrays above are the source of truth; keep this lookup here to
  // make the actual-Diff policy check independent from declared operation IDs.
  void before
  void after
  return [...targets.values()]
}

function checkInvariants(before: PpteDocument, after: PpteDocument, contract: ChangeContract): ValidationIssue[] {
  const issues: ValidationIssue[] = []
  const preserve = contract.preserve ?? {}
  const beforeElements = allElements(before)
  const afterElements = allElements(after)
  for (const [key, beforeElement] of beforeElements) {
    const afterElement = afterElements.get(key) ?? findReplacement(afterElements, beforeElement)
    if (!afterElement) {
      if (preserve.content === 'preserve' || preserve.data === 'preserve' || preserve.geometry === 'preserve' || preserve.style === 'preserve' || preserve.asset === 'preserve' || preserve.semanticIdentity === 'preserve' || preserve.semanticIdentity === 'allow-replacement') issues.push(issue('CHANGE_INVARIANT_VIOLATION', `Element ${key} was removed while an invariant is preserved.`, { elementId: key }))
      continue
    }
    if (preserve.content === 'preserve' && canonicalHash(contentProjection(beforeElement)) !== canonicalHash(contentProjection(afterElement))) issues.push(issue('CHANGE_INVARIANT_VIOLATION', `Content changed for ${key}.`, { elementId: key }))
    if (preserve.data === 'preserve' && canonicalHash(dataProjection(beforeElement)) !== canonicalHash(dataProjection(afterElement))) issues.push(issue('CHANGE_INVARIANT_VIOLATION', `Data changed for ${key}.`, { elementId: key }))
    if (preserve.style === 'preserve' && canonicalHash(styleProjection(beforeElement)) !== canonicalHash(styleProjection(afterElement))) issues.push(issue('CHANGE_INVARIANT_VIOLATION', `Style changed for ${key}.`, { elementId: key }))
    if (preserve.geometry === 'preserve' && canonicalHash(geometryProjection(beforeElement)) !== canonicalHash(geometryProjection(afterElement))) issues.push(issue('CHANGE_INVARIANT_VIOLATION', `Geometry changed for ${key}.`, { elementId: key }))
    if (preserve.asset === 'preserve' && canonicalHash(assetProjection(beforeElement)) !== canonicalHash(assetProjection(afterElement))) issues.push(issue('CHANGE_INVARIANT_VIOLATION', `Asset changed for ${key}.`, { elementId: key }))
    if (preserve.semanticIdentity === 'preserve' && (beforeElement.id !== afterElement.id || beforeElement.semanticKey !== afterElement.semanticKey)) issues.push(issue('CHANGE_INVARIANT_VIOLATION', `Semantic identity changed for ${key}.`, { elementId: key }))
    if (preserve.semanticIdentity === 'allow-replacement' && afterElement.id !== beforeElement.id && !isLineageReplacement(beforeElement, afterElement)) issues.push(issue('CHANGE_INVARIANT_VIOLATION', `Replacement for ${key} does not carry explicit lineage.`, { elementId: key }))
  }
  if (preserve.readingOrder === 'preserve' && canonicalHash(readingOrderProjection(before)) !== canonicalHash(readingOrderProjection(after))) issues.push(issue('CHANGE_INVARIANT_VIOLATION', 'Reading order changed while it is preserved.', { path: '/slides' }))
  if (preserve.facts === 'preserve' && canonicalHash(before.facts ?? {}) !== canonicalHash(after.facts ?? {})) issues.push(issue('CHANGE_INVARIANT_VIOLATION', 'Facts changed while they are preserved.', { path: '/facts' }))
  return issues
}

function checkProtectedAnchors(before: PpteDocument, after: PpteDocument, contract: ChangeContract): ValidationIssue[] {
  const issues: ValidationIssue[] = []
  for (const [slideId, slide] of Object.entries(before.slides)) {
    for (const anchor of slide.protectedAnchors ?? []) {
      const beforeElement = resolveAnchorElement(before, slideId, anchor)
      const afterElement = resolveAnchorElement(after, slideId, anchor)
      if (!afterElement && anchor.preserve.length > 0) {
        issues.push(issue('PROTECTED_ANCHOR_VIOLATION', 'Protected anchor no longer resolves.', { slideId }))
        continue
      }
      if (!beforeElement || !afterElement) continue
      for (const field of anchor.preserve) {
        const beforeValue = fieldProjection(beforeElement, field)
        const afterValue = fieldProjection(afterElement, field)
        if (canonicalHash(beforeValue) !== canonicalHash(afterValue)) issues.push(issue('PROTECTED_ANCHOR_VIOLATION', `Protected anchor field ${field} changed.`, { slideId, elementId: afterElement.id, semanticKey: afterElement.semanticKey }))
      }
    }
  }
  return issues
}

function resolveAnchorElement(document: PpteDocument, slideId: string, anchor: { target: { kind: string; elementId?: string; semanticKey?: string; factId?: string } }): Element | undefined {
  const slide = document.slides[slideId]
  if (!slide) return undefined
  if (anchor.target.kind === 'element') {
    const elementId = anchor.target.elementId ?? ''
    return slide.elements[elementId] ?? Object.values(slide.elements).find((element) => element.provenance?.replacesElementId === elementId)
  }
  if (anchor.target.kind === 'semantic') return Object.values(slide.elements).find((element) => element.semanticKey === anchor.target.semanticKey)
  if (anchor.target.kind === 'fact') return Object.values(slide.elements).find((element) => element.semanticRefs?.factIds?.includes(anchor.target.factId ?? ''))
  return undefined
}

function fieldProjection(element: Element, field: string): unknown {
  switch (field) {
    case 'content': return contentProjection(element)
    case 'data': return dataProjection(element)
    case 'style': return styleProjection(element)
    case 'geometry': return geometryProjection(element)
    case 'asset': return assetProjection(element)
    default: return undefined
  }
}
function contentProjection(element: Element): unknown {
  if (element.type === 'text') return richTextProjection(element.content)
  if (element.type === 'chart') return { data: element.data, encoding: element.encoding, options: element.options }
  if (element.type === 'component') return element.props
  return undefined
}
function richTextProjection(content: RichTextDocument): unknown {
  return {
    paragraphs: content.paragraphs.map((paragraph) => ({
      runs: paragraph.runs.map((run) => ({ text: run.text, ...(run.marks === undefined ? {} : { marks: run.marks }) })),
      ...(paragraph.align === undefined ? {} : { align: paragraph.align }),
      ...(paragraph.list === undefined ? {} : { list: paragraph.list }),
      ...(paragraph.spaceBefore === undefined ? {} : { spaceBefore: paragraph.spaceBefore }),
      ...(paragraph.spaceAfter === undefined ? {} : { spaceAfter: paragraph.spaceAfter }),
    })),
  }
}
function dataProjection(element: Element): unknown {
  return element.type === 'chart' ? { data: element.data, encoding: element.encoding } : undefined
}
function styleProjection(element: Element): unknown {
  if (element.type === 'text') return { style: element.style, paragraphStyle: element.paragraphStyle, boxStyle: element.boxStyle, overflowPolicy: element.overflowPolicy, opacity: element.opacity }
  if (element.type === 'shape') return { style: element.style, opacity: element.opacity }
  if (element.type === 'image') return { style: element.style, opacity: element.opacity }
  if (element.type === 'chart') return { style: element.style, opacity: element.opacity }
  return { opacity: element.opacity }
}
function geometryProjection(element: Element): unknown {
  return { frame: element.frame, rotationDeg: element.rotationDeg, flipX: element.flipX, flipY: element.flipY }
}
function assetProjection(element: Element): unknown {
  return element.type === 'image' ? { assetId: element.assetId, crop: element.crop, focalPoint: element.focalPoint } : undefined
}
function readingOrderProjection(document: PpteDocument): unknown {
  return document.slideOrder.map((slideId) => [slideId, (document.slides[slideId].readingOrder ?? []).map((elementId) => {
    const element = document.slides[slideId].elements[elementId]
    return element?.semanticKey ?? elementId
  })])
}
function allElements(document: PpteDocument): Map<string, Element> {
  const result = new Map<string, Element>()
  for (const slide of Object.values(document.slides)) for (const [elementId, element] of Object.entries(slide.elements)) result.set(elementId, element)
  return result
}
function findReplacement(afterElements: Map<string, Element>, beforeElement: Element): Element | undefined {
  return [...afterElements.values()].find((candidate) => isLineageReplacement(beforeElement, candidate))
}
function isLineageReplacement(beforeElement: Element, candidate: Element): boolean {
  return candidate.provenance?.replacesElementId === beforeElement.id || (Boolean(beforeElement.semanticKey) && candidate.provenance?.sourceSemanticKey === beforeElement.semanticKey)
}
function findElementSlide(document: PpteDocument, elementId: string): string | undefined {
  return document.slideOrder.find((slideId) => Boolean(document.slides[slideId]?.elements[elementId]))
}
function readPointer(root: unknown, path: string): unknown {
  if (!path || path === '/') return root
  let current: unknown = root
  for (const token of path.slice(1).split('/').map(unescapePointer)) {
    if (current === null || current === undefined || typeof current !== 'object') return undefined
    current = Array.isArray(current) ? current[Number(token)] : (current as Record<string, unknown>)[token]
  }
  return current
}
function unescapePointer(value: string): string {
  return value.replaceAll('~1', '/').replaceAll('~0', '~')
}
function pathMatches(path: string, allowed: string): boolean {
  return allowed === path || (allowed.endsWith('/*') && path.startsWith(allowed.slice(0, -1))) || path.startsWith(`${allowed}/`)
}
function pointer(value: string): string {
  return value.replaceAll('~', '~0').replaceAll('/', '~1')
}
function issue(code: string, message: string, extra: Partial<ValidationIssue> = {}): ValidationIssue {
  return withErrorSemantics({ code, severity: 'error', message, ...extra })
}
function dedupeIssues(issues: ValidationIssue[]): ValidationIssue[] {
  const seen = new Set<string>()
  return issues.filter((item) => {
    const key = `${item.code}|${item.message}|${item.path ?? ''}|${item.elementId ?? ''}`
    if (seen.has(key)) return false
    seen.add(key)
    return true
  })
}
