import { build } from 'esbuild';
import { writeFileSync, rmSync } from 'node:fs';
// dist is generated output; remove retired compiled tests after a checkout upgrade.
if (process.argv.includes('--clean')) rmSync('dist', { recursive: true, force: true });
const result = await build({ entryPoints: ['packages/html-document/src/runtime.ts'], bundle: true, write: false, platform: 'browser', format: 'iife', target: 'es2022', minify: true, legalComments: 'none', metafile: true });
writeFileSync('packages/html-document/src/runtime-bundle.ts', '// Generated by scripts/build-html.mjs\nexport const runtimeScript = ' + JSON.stringify(result.outputFiles[0].text) + ';\n');
